/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv_example_CameraToEdgeActivity */

#ifndef _Included_com_example_opencv_example_CameraToEdgeActivity
#define _Included_com_example_opencv_example_CameraToEdgeActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_opencv_example_CameraToEdgeActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_opencv_example_CameraToEdgeActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_opencv_example_CameraToEdgeActivity
 * Method:    detectEdgeJNI
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv_1example_CameraToEdgeActivity_detectEdgeJNI
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
