/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv_example_CameraToGrayActivity */

#ifndef _Included_com_example_opencv_example_CameraToGrayActivity
#define _Included_com_example_opencv_example_CameraToGrayActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_opencv_example_CameraToGrayActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_opencv_example_CameraToGrayActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_opencv_example_CameraToGrayActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv_1example_CameraToGrayActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
